CREATE OR REPLACE PROCEDURE ADICIONAR_RESERVA(
  COD_CLIENTE CLIENTES.CODIGO%TYPE,
  NRO_MESA NUMBER,
  HORARIO_RESERVA DATE
)IS
  RESTAURANTE_ABERTO NUMBER(1) := RESTAURANTE_ABERTO(HORARIO_RESERVA);
  RESTAURANTE_ABERTO_FERIADO NUMBER(1) := RESTAURANTE_ABERTO_FERIADO(HORARIO_RESERVA);
  COUNT_RESERVA NUMBER;
  COUNT_MESA NUMBER;
  NOME_C VARCHAR2(50);
  TEL_C VARCHAR2(25);
  INSERT_LISTA_ESPERA EXCEPTION;
  RESTAURANTE_FECHADO EXCEPTION;
  MESA_OCUPADA EXCEPTION;
  CURSOR P_CUR IS
    SELECT NOME, TELEFONE 
    FROM CLIENTES
    WHERE CÓDIGO = COD_CLIENTE;
  
BEGIN
  IF(RESTAURANTE_ABERTO = 1) THEN
    IF(RESTAURANTE_ABERTO_FERIADO = 1) THEN 
      SELECT COUNT(*) INTO COUNT_RESERVA
      FROM RESERVAS;
        IF(COUNT_RESERVA < 6) THEN
          SELECT COUNT(NUM_MESA) INTO COUNT_MESA
          FROM RESERVAS
          WHERE NUM_MESA = NRO_MESA;
          
          IF(COUNT_MESA = 0) THEN
            INSERT INTO RESERVA
            VALUES(COD_CLIENTE, NRO_MESA, HORARIO_RESERVA);
          ELSE
            RAISE MESA_OCUPADA;
          END IF;
        ELSE
          RAISE INSERT_LISTA_ESPERA;
          
          SELECT NOME, TELEFONE INTO NOME_C, TEL_C
          FROM CLIENTE
          WHERE CODIGO = COD_CLIENTE;
          
          INSERT INTO LISTA_ESPERA
          VALUES(NOME_C, TEL_C, HORARIO_RESERVA);
        END IF;
      END IF;
  ELSE
    RAISE RESTAURANTE_FECHADO;
  END IF;
  
EXCEPTION
  WHEN INSERT_LISTA_ESPERA THEN
    DBMS_OUTPUT.PUT_LINE('Não há mesas disponíveis. Cliente inserido na lista de espera.');
  WHEN RESTAURANTE_FECHADO THEN
    DBMS_OUTPUT.PUT_LINE('O restaurante não abre na data passada.');
  WHEN MESA_OCUPADA THEN
    DBMS_OUTPUT.PUT_LINE('A mesa desejada já está ocupada');
END;
/