CREATE OR REPLACE FUNCTION RESTAURANTE_ABERTO_FERIADO(
  DATA_CONSULTA DATE
)
RETURN NUMBER IS
  V_DIA_ABERTO NUMBER(1);
  V_ABERTURA_FERIADO VARCHAR2(5);
  V_FECHAMENTO_FERIADO VARCHAR2(5);
  V_ABERTO NUMBER(1) := 0;
BEGIN
  SELECT EM_FUNCIONAMENTO, ABERTURA_FERIADO, FECHAMENTO_FERIADO
  INTO V_DIA_ABERTO, V_ABERTURA_FERIADO, V_FECHAMENTO_FERIADO
  FROM HORARIO_FUNCIONAMENTO
  WHERE DIA_SEMANA = SEMANA_NUMERO(DATA_CONSULTA);

  IF(V_DIA_ABERTO = '1') THEN
    IF(TO_CHAR(DATA_CONSULTA, 'HH24:MI') BETWEEN V_ABERTURA_FERIADO AND V_FECHAMENTO_FERIADO)  THEN
      V_ABERTO := 1;
    END IF;
  END IF;
  RETURN V_ABERTO;
END;
/
