<<<<<<< HEAD
CREATE OR REPLACE FUNCTION RESTAURANTE_ABERTO_FERIADO(
  DATA_CONSULTA DATE
)
RETURN NUMBER IS
  V_DIA_ABERTO NUMBER(1);
  V_ABERTURA_FERIADO VARCHAR2(5);
  V_FECHAMENTO_FERIADO VARCHAR2(5);
  V_ABERTO NUMBER(1) := 0;
BEGIN
  SELECT EM_FUNCIONAMENTO, ABERTURA_FERIADO, FECHAMENTO_FERIADO
  INTO V_DIA_ABERTO, V_ABERTURA_FERIADO, V_FECHAMENTO_FERIADO
  FROM HORARIO_FUNCIONAMENTO
  WHERE DIA_SEMANA = SEMANA_NUMERO(DATA_CONSULTA);

  IF(V_DIA_ABERTO = '1') THEN
    IF(TO_CHAR(DATA_CONSULTA, 'HH24:MI') BETWEEN V_ABERTURA_FERIADO AND V_FECHAMENTO_FERIADO)  THEN
=======
-- Verifica se o restaurante está em funcionamento nos feriados
-- Recebe DATE Dia e horário para verificar funcionamento
-- Retorna CHAR 1 - Aberto ou 0 - Fechado
CREATE OR REPLACE FUNCTION RESTAURANTE_ABERTO_FERIADO(
  HORA_CONSULTA DATE
)
RETURN NUMBER IS
  V_DIA_ABERTO NUMBER(1);
  V_HORA_ABERTURA VARCHAR2(5);
  V_HORA_FECHAMENTO VARCHAR2(5);
  V_ABERTO NUMBER(1) := 0;
BEGIN
  SELECT EM_FUNCIONAMENTO, ABERTURA_FERIADO, FECHAMENTO_FERIADO
  INTO V_DIA_ABERTO, V_HORA_ABERTURA, V_HORA_FECHAMENTO
  FROM HORARIO_FUNCIONAMENTO
  WHERE DIA_SEMANA = SEMANA_NUMERO(HORA_CONSULTA);

  IF(V_DIA_ABERTO = '1') THEN
    IF(TO_CHAR(HORA_CONSULTA, 'HH24:MI') BETWEEN V_HORA_ABERTURA AND V_HORA_FECHAMENTO)  THEN
>>>>>>> f32a8784cb8d9f7f06436e56bfcf7109018e5efd
      V_ABERTO := 1;
    END IF;
  END IF;
  RETURN V_ABERTO;
END;
/
