--Função para calcular o valor total das comidas
CREATE OR REPLACE FUNCTION VALOR_COMIDA(
  I_COD_COMIDA COMIDAS.CODIGO%TYPE
)
RETURN NUMBER IS
  VALOR_TOTAL NUMBER := 0;
  VALOR_ITEM NUMBER;

  CURSOR P_CUR IS
    SELECT CI.QUANTIDADE, I.VALOR, C.PCT_LUCRO
    FROM COMIDAS C
    INNER JOIN COMIDA_ITENS CI
      ON C.CODIGO = CI.COD_COMIDA
    INNER JOIN ITENS I
      ON CI.COD_ITEM = I.CODIGO
    WHERE C.CODIGO = I_COD_COMIDA;
BEGIN

  FOR R_CUR IN P_CUR LOOP
    VALOR_ITEM := (R_CUR.QUANTIDADE * R_CUR.VALOR) + ((R_CUR.QUANTIDADE * R_CUR.VALOR * R_CUR.PCT_LUCRO)/100);
    VALOR_TOTAL := VALOR_TOTAL + VALOR_ITEM;
  END LOOP;

  RETURN VALOR_TOTAL;
END;
/

BEGIN
  DBMS_OUTPUT.PUT_LINE(VALOR_COMIDA(3));
END;
/
