--Função para calcular o valor total do pedido
CREATE OR REPLACE FUNCTION VALOR_PEDIDO(
  I_COD_COMIDA COMIDAS.CODIGO%TYPE,
  I_COD_BEBIDAP BEBIDAS_PRONTAS.CODIGO%TYPE,
  I_COD_BEBIDA BEBIDAS.CODIGO%TYPE
)
RETURN NUMBER IS
  VALOR_TOTAL NUMBER := 0;
  VALOR_BEBIDA NUMBER;
  VALOR_ITEMB NUMBER;
  VALOR_BEBIDAP NUMBER;
  VALOR_ITEMBP NUMBER;
  VALOR_COMIDA NUMBER;
  VALOR_ITEMC NUMBER;
  VALORTOTB NUMBER;
  VALORB NUMBER;
  PCT NUMBER;

  CURSOR C_CUR IS
    SELECT CI.QUANTIDADE, I.VALOR, C.PCT_LUCRO
    FROM COMIDAS C
    INNER JOIN COMIDA_ITENS CI
      ON C.CODIGO = CI.COD_COMIDA
    INNER JOIN ITENS I
      ON CI.COD_ITEM = I.CODIGO
    WHERE C.CODIGO = I_COD_COMIDA;

  CURSOR B_CUR IS
    SELECT BI.QUANTIDADE, I.VALOR, B.PCT_LUCRO
    FROM BEBIDAS B
    INNER JOIN BEBIDA_ITENS BI
      ON B.CODIGO = BI.COD_BEBIDA
    INNER JOIN ITENS I
      ON BI.COD_ITEM = I.CODIGO
    WHERE B.CODIGO = I_COD_BEBIDA;

BEGIN
    SELECT I.VALOR, BP.PCT_LUCRO INTO VALORB, PCT
    FROM BEBIDAS_PRONTAS BP
    INNER JOIN ITENS I
      ON BP.COD_ITEM = I.CODIGO
    WHERE BP.CODIGO = I_COD_BEBIDAP;

    VALORTOTB := VALORB + ((VALORB * PCT)/100);

    FOR R_CUR IN C_CUR LOOP
      VALOR_ITEMC := (R_CUR.QUANTIDADE * R_CUR.VALOR) + ((R_CUR.QUANTIDADE * R_CUR.VALOR * R_CUR.PCT_LUCRO)/100);
      VALOR_COMIDA := VALOR_COMIDA + VALOR_ITEMC;
    END LOOP;

    FOR R_CUR IN B_CUR LOOP
      VALOR_ITEMB := (R_CUR.QUANTIDADE * R_CUR.VALOR) + ((R_CUR.QUANTIDADE * R_CUR.VALOR * R_CUR.PCT_LUCRO)/100);
      VALOR_BEBIDA := VALOR_BEBIDA + VALOR_ITEMB;
    END LOOP;

    VALOR_TOTAL := VALORTOTB + VALOR_COMIDA + VALOR_BEBIDA;

    RETURN VALOR_TOTAL;
END;
/

SET SERVEROUTPUT ON;

BEGIN
  DBMS_OUTPUT.PUT_LINE(VALOR_PEDIDO(1, 1, 1));
END;
/
