-- Fecha a comanda finalizando preço de serviço
-- Recebe NUMBER Código Comanda, CHAR Forma de Pagamento, VARCHAR2 Operadora
CREATE OR REPLACE PROCEDURE FECHAR_COMANDA(
  I_COD_COMANDA COMANDAS.CODIGO%TYPE,
  I_FORMA_PAGAMENTO COMANDAS.FORMA_PAGAMENTO%TYPE,
  I_OPERADORA COMANDAS.OPERADORA%TYPE
)
IS
  EX_COMANDA_INVALIDA EXCEPTION;
  EX_FORMA_PAGTO_INVALIDA EXCEPTION;
  V_COUNT_COMANDAS NUMBER;
BEGIN
  COMMIT;

  SELECT COUNT(CODIGO) INTO V_COUNT_COMANDAS
  FROM COMANDAS
  WHERE CODIGO = I_COD_COMANDA;

  IF V_COUNT_COMANDAS < 1 THEN
    RAISE EX_COMANDA_INVALIDA;
  END IF;

  IF I_FORMA_PAGAMENTO NOT IN ('C', 'D', 'M') THEN
    RAISE EX_FORMA_PAGTO_INVALIDA;
  END IF;

  UPDATE COMANDAS
  SET HORA_FINAL = SYSDATE,
    VALOR = VALOR + COUVERT,
    FORMA_PAGAMENTO = I_FORMA_PAGAMENTO,
    OPERADORA = I_OPERADORA
  WHERE CODIGO = I_COD_COMANDA;

  COMMIT;
  EXCEPTION
    WHEN EX_COMANDA_INVALIDA THEN
      ROLLBACK;
      DBMS_OUTPUT.PUT_LINE('Código da Comanda inválido');
    WHEN EX_FORMA_PAGTO_INVALIDA THEN
      ROLLBACK;
      DBMS_OUTPUT.PUT_LINE('Forma de pagamento inválida');
END;
/
