-- Tabela de Bebidas Prontas
CREATE TABLE BEBIDAS_PRONTAS(
  CODIGO NUMBER(9) NOT NULL PRIMARY KEY
    REFERENCES CARDAPIO_OPCOES(CODIGO),
  VALOR NUMBER(8,2) NOT NULL,
  COD_ESTOQUE NUMBER(9) NOT NULL
    REFERENCES ESTOQUE(CODIGO)
);
