-- Tabela de Bebida_Itens
CREATE TABLE BEBIDA_ITENS(
  COD_BEBIDA NUMBER(9) NOT NULL
    REFERENCES BEBIDAS(CODIGO),
  COD_ITEM NUMBER(9) NOT NULL
    REFERENCES ITENS(CODIGO),
  QUANTIDADE NUMBER(9) NOT NULL,
  CONSTRAINT PK_BEBIDA_ITENS
    PRIMARY KEY(COD_BEBIDA, COD_ITEM)
);
