-- Tabela de Opções na Comanda
CREATE TABLE COMANDA_OPCOES(
  CODIGO NUMBER(9) NOT NULL PRIMARY KEY,
  COD_COMANDA NUMBER(9) NOT NULL
    REFERENCES COMANDAS(CODIGO),
  COD_OPCAO NUMBER(9) NOT NULL
    REFERENCES OPCOES(CODIGO),
  QUANTIDADE NUMBER(9) NOT NULL
);
