--Tabela dos comandos
CREATE TABLE COMANDAS(
  CODIGO NUMBER(9) PRIMARY KEY NOT NULL,
  VALOR NUMBER(8,2) NOT NULL,
  QTD_PESSOAS NUMBER(2) NOT NULL,
  COD_ATENDENTE NUMBER(9) NOT NULL
    REFERENCES ATENDENTES(CODIGO)
);
