-- Tabela de Consumos
CREATE TABLE CONSUMOS(
  NOTA_FISCAL NUMBER(9) NOT NULL PRIMARY KEY,
  DIA DATE NOT NULL,
  HORA_INICIO VARCHAR2(5),
  HORA_FINAL VARCHAR2(5),
  COUVERT NUMBER(8,2),
  OPERADORA VARCHAR2(25),
  FORMA_PAGAMENTO CHAR(1),
  CONSTRAINT CK_FORMA_PAGAMENTO
    CHECK(FORMA_PAGAMENTO IN('C', 'D', 'M')),
  COD_COMANDA NUMBER(9) NOT NULL
    REFERENCES COMANDAS(CODIGO)
);
