-- Tabela de Clientes
CREATE TABLE CLIENTES(
  CODIGO NUMBER(9) NOT NULL PRIMARY KEY,
  NOME VARCHAR2(50) NOT NULL,
  TELEFONE VARCHAR2(25) NOT NULL,
  CONSTRAINT UN_CLIENTES
    UNIQUE(NOME, TELEFONE)
);
