-- Tabela de Opções de Cardápio
CREATE TABLE CARDAPIO_OPCOES(
  CODIGO NUMBER(9) NOT NULL PRIMARY KEY,
  DESCRICAO VARCHAR2(50) NOT NULL,
  PCT_LUCRO NUMBER(9) NOT NULL,
  TIPO CHAR(1) NOT NULL,
  CONSTRAINT CK_OPCAO_TIPO
    CHECK(TIPO IN('B', 'BP', 'C'))
);
