-- Tabela de Comandas
CREATE TABLE COMANDAS(
  CODIGO NUMBER(9) NOT NULL PRIMARY KEY,
  COD_ATENDENTE NUMBER(9) NOT NULL
    REFERENCES ATENDENTES(CODIGO),
  COD_MESA NUMBER(3) NOT NULL
    REFERENCES MESAS(NUMERO),
  HORA_INICIO TIMESTAMP NOT NULL,
  HORA_FINAL TIMESTAMP,
  QTD_PESSOAS NUMBER(2) NOT NULL,
  COUVERT NUMBER(8,2),
  VALOR NUMBER(8,2),
  FORMA_PAGAMENTO CHAR(1),
  OPERADORA VARCHAR2(25),
  CONSTRAINT UN_COMANDA
    UNIQUE(COD_MESA, HORA_INICIO),
  CONSTRAINT CK_FORMA_PAGAMENTO
    CHECK(FORMA_PAGAMENTO IN ('C', 'D', 'M'))
);
