--TABELA HORARIO RESTAURANTE
CREATE TABLE HORARIO_FUNCIONAMENTO(
  DIA_SEMANA NUMBER(1) NOT NULL PRIMARY KEY,
  EM_FUNCIONAMENTO NUMBER(1) NOT NULL,
  HORA_ABERTURA VARCHAR2(5),
  HORA_FECHAMENTO VARCHAR2(5),
  ABERTURA_FERIADO VARCHAR2(5),
  FECHAMENTO_FERIADO VARCHAR2(5),
  CONSTRAINT chk_EM_FUNCIONAMENTO
    CHECK (EM_FUNCIONAMENTO IN (0, 1))
);
