-- Tabela de Itens
CREATE TABLE ITENS(
  CODIGO NUMBER(9) NOT NULL PRIMARY KEY,
  DESCRICAO VARCHAR2(50) NOT NULL,
  VALOR NUMBER(8,2) NOT NULL,
  ESTOQUE NUMBER(9) NOT NULL,
  CONSTRAINT CK_ESTOQUE
    CHECK(ESTOQUE > 0)
);
