-- Tabela de Opções
CREATE TABLE OPCOES(
  CODIGO NUMBER(9) NOT NULL PRIMARY KEY,
  DESCRICAO VARCHAR2(50) NOT NULL,
  PCT_LUCRO NUMBER(4,2) DEFAULT 0.00 NOT NULL,
  TIPO CHAR(1) NOT NULL,
  CONSTRAINT CK_OPCAO_TIPO
    CHECK(TIPO IN('B', 'P', 'C'))
);
