-- Tabela de Pedidos
CREATE TABLE PEDIDOS(
  CODIGO NUMBER(9) NOT NULL PRIMARY KEY,
  TIPO CHAR(1) NOT NULL,
  COD_OPCAO NUMBER(9) NOT NULL,
  QUANTIDADE NUMBER(9) NOT NULL,
  COD_COMANDA NUMBER(9) NOT NULL
    REFERENCES COMANDAS(CODIGO),
  COD_MESA NUMBER(3) NOT NULL
    REFERENCES MESAS(NUMERO),
  CONSTRAINT CK_TIPO
    CHECK(TIPO IN('C', 'B', 'P'))
);
