--TABELA RESERVA
CREATE TABLE RESERVA(
  NOMEC VARCHAR2(50) NOT NULL,
  TELEFONEC VARCHAR2(25) NOT NULL,
  NUM_MESA NUMBER(3, 0) NOT NULL,
  DIA DATE NOT NULL,
  HORARIO VARCHAR2(5)
  --QTD_INTEGRANTES NUMBER
  );