-- Tabela de Reservas
CREATE TABLE RESERVAS(
  COD_CLIENTE NUMBER(9) NOT NULL
    REFERENCES CLIENTES(CODIGO),
  NUM_MESA NUMBER(3,0) NOT NULL
    REFERENCES MESAS(NUMERO),
  DIA DATE NOT NULL,
  CONSTRAINT PK_RESERVAS
    PRIMARY KEY(COD_CLIENTE, NUM_MESA, DIA)
);
