-- Usu√°rio para cria√ß√£o do projeto
CREATE USER PROJETODSIBD
IDENTIFIED BY projetodsibd
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION
, CREATE TABLE
, CREATE SEQUENCE
, CREATE TRIGGER
, CREATE PROCEDURE
, CREATE VIEW
TO PROJETODSIBD;

---------------------------------------
--Usu·rio para os gerentes
CREATE USER GERENTE
IDENTIFIED BY gerente
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

CREATE ROLE gerentes;

GRANT CREATE SESSION,
      CREATE VIEW,
      CREATE PROCEDURE
TO gerentes;

GRANT gerentes TO GERENTE WITH ADMIN OPTION;

GRANT SELECT,
      INSERT,
      UPDATE,
      DELETE
ON PROJETODSIBD.ATENDENTES
TO GERENTE;

---------------------------------------------
--Usu·rio para os atendentes
CREATE USER ATENDENTE
IDENTIFIED BY atendente
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION,
      CREATE VIEW
TO ATENDENTE;
