-- Usuário para criação do projeto
CREATE USER PROJETODSIBD
IDENTIFIED BY projetodsibd
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION
, CREATE TABLE
, CREATE SEQUENCE
, CREATE TRIGGER
, CREATE PROCEDURE
TO PROJETODSIBD;
