-- Usu√°rio para cria√ß√£o do projeto
CREATE USER PROJETODSIBD
IDENTIFIED BY projetodsibd
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION
, CREATE TABLE
, CREATE SEQUENCE
, CREATE TRIGGER
, CREATE PROCEDURE
, CREATE VIEW
TO PROJETODSIBD;

---------------------------------------
--Usu·rio para os gerentes
CREATE USER GERENTE
IDENTIFIED BY gerente
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

CREATE ROLE gerentes;

GRANT CREATE SESSION
TO gerentes;

GRANT gerentes TO GERENTE WITH ADMIN OPTION;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.ATENDENTES
TO GERENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.HORARIO_FUNCIONAMENTO
TO GERENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.MESAS
TO GERENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.CLIENTES
TO GERENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.LISTA_ESPERA
TO GERENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.RESERVAS
TO GERENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.OPCOES
TO GERENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.BEBIDAS
TO GERENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.COMIDAS
TO GERENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.COMANDAS
TO GERENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.COMANDA_OPCOES
TO GERENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.ESTOQUE
TO GERENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.ITENS_EM_FALTA
TO GERENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.BEBIDAS_PRONTAS
TO GERENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.VINHOS
TO GERENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.ITENS
TO GERENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.COMIDA_ITENS
TO GERENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.BEBIDA_ITENS
TO GERENTE;

---------------------------------------------
--Usu·rio para os atendentes
CREATE USER ATENDENTE
IDENTIFIED BY atendente
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION
TO ATENDENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.HORARIO_FUNCIONAMENTO
TO ATENDENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.MESAS
TO ATENDENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.CLIENTES
TO ATENDENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.LISTA_ESPERA
TO ATENDENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.RESERVAS
TO ATENDENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.OPCOES
TO ATENDENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.BEBIDAS
TO ATENDENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.COMIDAS
TO ATENDENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.COMANDAS
TO ATENDENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.COMANDA_OPCOES
TO ATENDENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.ESTOQUE
TO ATENDENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.ITENS_EM_FALTA
TO ATENDENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.BEBIDAS_PRONTAS
TO ATENDENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.VINHOS
TO ATENDENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.ITENS
TO ATENDENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.COMIDA_ITENS
TO ATENDENTE;

GRANT SELECT, INSERT, UPDATE, DELETE
ON PROJETODSIBD.BEBIDA_ITENS
TO ATENDENTE;