-- Criação de todas as views

-- View para itens e quantidade em estoque
CREATE OR REPLACE VIEW ITENS_ESTOQUE AS 
  SELECT I.DESCRICAO, E.QUANTIDADE
  FROM ITENS I
  JOIN ESTOQUE E
    ON I.COD_ESTOQUE = E.CODIGO;

SELECT * FROM ITENS_ESTOQUE;

-- View para dizer os itens mais consumidos por uma mesa
CREATE OR REPLACE VIEW ITENS_MAIS_CONSUMIDOS AS
  SELECT I.DESCRICAO, CO.QUANTIDADE
  FROM ITENS I
  JOIN COMIDA_ITENS CI
    ON CI.COD_ITEM = I.CODIGO
  JOIN COMIDAS C
    ON C.CODIGO = CI.COD_COMIDA
  JOIN OPCOES O
    ON O.CODIGO = C.CODIGO
  JOIN BEBIDA_ITENS BI
    ON BI.COD_ITEM = I.CODIGO
  JOIN BEBIDAS B
    ON B.CODIGO = BI.COD_BEBIDA
  JOIN OPCOES O
    ON O.CODIGO = B.CODIGO
  JOIN BEBIDAS_PRONTAS BP
    ON O.CODIGO = BP.CODIGO
  JOIN COMANDA_OPCOES CO
    ON CO.COD_OPCAO = O.CODIGO
  JOIN COMANDAS CM
    ON CO.COD_COMANDA = CM.CODIGO
  JOIN MESAS M
    ON M.NUMERO = CM.COD_MESA
  ORDER BY CO.QUANTIDADE DESC;
    
SELECT * FROM ITENS_MAIS_CONSUMIDOS;