--Cria todas as sequências geradoras de códigos

--Sequência para os gerentes
CREATE SEQUENCE COD_GERENTES
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999
NOCACHE
NOCYCLE;

--Sequência para os atendentes
CREATE SEQUENCE COD_ATENDENTES
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999
NOCACHE
NOCYCLE;

--Sequência para os clientes
CREATE SEQUENCE COD_CLIENTES
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999
NOCACHE
NOCYCLE;

--Sequência para as opções
CREATE SEQUENCE COD_OPCOES
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999
NOCACHE
NOCYCLE;

--Sequência para as comandas
CREATE SEQUENCE COD_COMANDA
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999
NOCACHE
NOCYCLE;

--Sequência para as comandas_opções
CREATE SEQUENCE COD_COMANDA_OP
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999
NOCACHE
NOCYCLE;

--Sequência para o estoque
CREATE SEQUENCE COD_ESTOQUE
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999
NOCACHE
NOCYCLE;

--Sequência para os itens
CREATE SEQUENCE COD_ITENS
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999
NOCACHE
NOCYCLE;