-- Cria todas as tabelas

--TABELA HORARIO RESTAURANTE
CREATE TABLE HORARIO_FUNCIONAMENTO(
  DIA_SEMANA NUMBER(1) NOT NULL PRIMARY KEY,
  EM_FUNCIONAMENTO NUMBER(1) NOT NULL,
  HORA_ABERTURA VARCHAR2(5),
  HORA_FECHAMENTO VARCHAR2(5),
  ABERTURA_FERIADO VARCHAR2(5),
  FECHAMENTO_FERIADO VARCHAR2(5),
  CONSTRAINT chk_EM_FUNCIONAMENTO
    CHECK (EM_FUNCIONAMENTO IN (0, 1))
);

--TABELA LISTA DE ESPERA
CREATE TABLE LISTA_ESPERA(
  NOME_C VARCHAR2(50) NOT NULL,
  TELEFONE_C VARCHAR2(25) NOT NULL,
  DIA DATE NOT NULL);

-- Tabela de Mesas
CREATE TABLE MESAS(
  NUMERO NUMBER(3,0) NOT NULL,
  CONSTRAINT PK_MESAS
    PRIMARY KEY(NUMERO)
);

-- Tabela de Gerentes
CREATE TABLE GERENTES(
  CODIGO NUMBER(9) NOT NULL PRIMARY KEY,
  NOME VARCHAR2(50) NOT NULL
);

-- Tabela de Atendentes
CREATE TABLE ATENDENTES(
  CODIGO NUMBER(9) NOT NULL PRIMARY KEY,
  NOME VARCHAR2(50) NOT NULL,
  COD_GERENTE NUMBER(9)
    REFERENCES GERENTES(CODIGO)
    ON DELETE SET NULL
);

-- Tabela de Clientes
CREATE TABLE CLIENTES(
  CODIGO NUMBER(9) NOT NULL PRIMARY KEY,
  NOME VARCHAR2(50) NOT NULL,
  TELEFONE VARCHAR2(25) NOT NULL,
  CONSTRAINT UN_CLIENTES
    UNIQUE(NOME, TELEFONE)
);

-- Tabela de Reservas
CREATE TABLE RESERVAS(
  COD_CLIENTE NUMBER(9) NOT NULL
    REFERENCES CLIENTES(CODIGO),
  NUM_MESA NUMBER(3,0) NOT NULL
    REFERENCES MESAS(NUMERO),
  DIA DATE NOT NULL,
  CONSTRAINT PK_RESERVAS
    PRIMARY KEY(COD_CLIENTE, NUM_MESA, DIA)
);

-- Tabela de Opções
CREATE TABLE OPCOES(
  CODIGO NUMBER(9) NOT NULL PRIMARY KEY,
  DESCRICAO VARCHAR2(50) NOT NULL,
  PCT_LUCRO NUMBER(4,2) DEFAULT 0.00 NOT NULL,
  TIPO CHAR(1) NOT NULL,
  CONSTRAINT CK_OPCAO_TIPO
    CHECK(TIPO IN('B', 'P', 'C'))
);

-- Tabela de Bebidas
CREATE TABLE BEBIDAS(
  CODIGO NUMBER(9) NOT NULL PRIMARY KEY
    REFERENCES OPCOES(CODIGO)
);

-- Tabela de Comidas
CREATE TABLE COMIDAS(
  CODIGO NUMBER(9) NOT NULL PRIMARY KEY
    REFERENCES OPCOES(CODIGO)
);

-- Tabela de Comandas
CREATE TABLE COMANDAS(
  CODIGO NUMBER(9) NOT NULL PRIMARY KEY,
  COD_ATENDENTE NUMBER(9) NOT NULL
    REFERENCES ATENDENTES(CODIGO),
  COD_MESA NUMBER(3) NOT NULL
    REFERENCES MESAS(NUMERO),
  HORA_INICIO TIMESTAMP NOT NULL,
  HORA_FINAL TIMESTAMP,
  QTD_PESSOAS NUMBER(2) NOT NULL,
  COUVERT NUMBER(8,2),
  VALOR NUMBER(8,2) DEFAULT 0.00 NOT NULL,
  FORMA_PAGAMENTO CHAR(1),
  OPERADORA VARCHAR2(25),
  CONSTRAINT UN_COMANDA
    UNIQUE(COD_MESA, HORA_INICIO),
  CONSTRAINT CK_VALOR
    CHECK(VALOR >= 0.00),
  CONSTRAINT CK_FORMA_PAGAMENTO
    CHECK(FORMA_PAGAMENTO IN ('C', 'D', 'M'))
);

-- Tabela de Opções na Comanda
CREATE TABLE COMANDA_OPCOES(
  CODIGO NUMBER(9) NOT NULL PRIMARY KEY,
  COD_COMANDA NUMBER(9) NOT NULL
    REFERENCES COMANDAS(CODIGO),
  COD_OPCAO NUMBER(9) NOT NULL
    REFERENCES OPCOES(CODIGO),
  QUANTIDADE NUMBER(9) NOT NULL
);

-- Tabela de Estoque
CREATE TABLE ESTOQUE(
  CODIGO NUMBER(9) NOT NULL PRIMARY KEY,
  QUANTIDADE NUMBER(9) NOT NULL
    CONSTRAINT CK_ESTOQUE
    CHECK(QUANTIDADE >= 0)
);

-- Tabela de Bebidas Prontas
CREATE TABLE BEBIDAS_PRONTAS(
  CODIGO NUMBER(9) NOT NULL PRIMARY KEY
    REFERENCES OPCOES(CODIGO),
  VALOR NUMBER(8,2) NOT NULL,
  COD_ESTOQUE NUMBER(9) NOT NULL
    REFERENCES ESTOQUE(CODIGO)
);

-- Tabela de Vinhos
CREATE TABLE VINHOS(
  CODIGO NUMBER(9) NOT NULL PRIMARY KEY
    REFERENCES BEBIDAS_PRONTAS(CODIGO),
  SAFRA NUMBER(4) NOT NULL,
  TIPO_UVA VARCHAR2(50) NOT NULL
);

-- Tabela de Itens
CREATE TABLE ITENS(
  CODIGO NUMBER(9) NOT NULL PRIMARY KEY,
  DESCRICAO VARCHAR2(50) NOT NULL UNIQUE,
  VALOR NUMBER(8,2) NOT NULL,
  COD_ESTOQUE NUMBER(9) NOT NULL
    REFERENCES ESTOQUE(CODIGO)
);

-- Tabela de Comida_Itens
CREATE TABLE COMIDA_ITENS(
  COD_COMIDA NUMBER(9) NOT NULL
    REFERENCES COMIDAS(CODIGO),
  COD_ITEM NUMBER(9) NOT NULL
    REFERENCES ITENS(CODIGO),
  QUANTIDADE NUMBER(9) NOT NULL,
  CONSTRAINT PK_COMIDA_ITENS
    PRIMARY KEY(COD_COMIDA, COD_ITEM)
);

-- Tabela de Bebida_Itens
CREATE TABLE BEBIDA_ITENS(
  COD_BEBIDA NUMBER(9) NOT NULL
    REFERENCES BEBIDAS(CODIGO),
  COD_ITEM NUMBER(9) NOT NULL
    REFERENCES ITENS(CODIGO),
  QUANTIDADE NUMBER(9) NOT NULL,
  CONSTRAINT PK_BEBIDA_ITENS
    PRIMARY KEY(COD_BEBIDA, COD_ITEM)
);
