--Cria todas as sequências geradoras de códigos

--Sequência para os gerentes
CREATE SEQUENCE SEQ_GERENTES
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999
NOCACHE
NOCYCLE;

--Sequência para os atendentes
CREATE SEQUENCE SEQ_ATENDENTES
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999
NOCACHE
NOCYCLE;

--Sequência para os clientes
CREATE SEQUENCE SEQ_CLIENTES
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999
NOCACHE
NOCYCLE;

--Sequência para as opções
CREATE SEQUENCE SEQ_OPCOES
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999
NOCACHE
NOCYCLE;

--Sequência para as comandas
CREATE SEQUENCE SEQ_COMANDA
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999
NOCACHE
NOCYCLE;

--Sequência para as comandas_opções
CREATE SEQUENCE SEQ_COMANDA_OP
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999
NOCACHE
NOCYCLE;

--Sequência para o estoque
CREATE SEQUENCE SEQ_ESTOQUE
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999
NOCACHE
NOCYCLE;

--Sequência para os itens
CREATE SEQUENCE SEQ_ITENS
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999
NOCACHE
NOCYCLE;
