--Exclui todas as sequências
DROP SEQUENCE SEQ_GERENTES;
DROP SEQUENCE SEQ_ATENDENTES;
DROP SEQUENCE SEQ_CLIENTES;
DROP SEQUENCE SEQ_OPCOES;
DROP SEQUENCE SEQ_COMANDA;
DROP SEQUENCE SEQ_COMANDA_OP;
DROP SEQUENCE SEQ_ESTOQUE;
DROP SEQUENCE SEQ_ITENS;
