--Exclui todas as sequências
DROP SEQUENCE COD_GERENTES;
DROP SEQUENCE COD_ATENDENTES;
DROP SEQUENCE COD_CLIENTES;
DROP SEQUENCE COD_OPCOES;
DROP SEQUENCE COD_COMANDA;
DROP SEQUENCE COD_COMANDA_OP;
DROP SEQUENCE COD_ESTOQUE;
DROP SEQUENCE COD_ITENS;
