-- Inserindo Horário de Funcionamento
INSERT INTO HORARIO_FUNCIONAMENTO
 (DIA_SEMANA, EM_FUNCIONAMENTO, HORA_ABERTURA, HORA_FECHAMENTO, ABERTURA_FERIADO, FECHAMENTO_FERIADO)
VALUES (1, 1, '19:00', '23:59', '19:00', '23:59');
INSERT INTO HORARIO_FUNCIONAMENTO
 (DIA_SEMANA, EM_FUNCIONAMENTO, HORA_ABERTURA, HORA_FECHAMENTO, ABERTURA_FERIADO, FECHAMENTO_FERIADO)
VALUES (2, 0, NULL, NULL, NULL, NULL);
INSERT INTO HORARIO_FUNCIONAMENTO
 (DIA_SEMANA, EM_FUNCIONAMENTO, HORA_ABERTURA, HORA_FECHAMENTO, ABERTURA_FERIADO, FECHAMENTO_FERIADO)
VALUES (3, 1, '19:00', '23:59', '19:00', '23:59');
INSERT INTO HORARIO_FUNCIONAMENTO
 (DIA_SEMANA, EM_FUNCIONAMENTO, HORA_ABERTURA, HORA_FECHAMENTO, ABERTURA_FERIADO, FECHAMENTO_FERIADO)
VALUES (4, 1, '19:00', '23:59', '19:00', '23:59');
INSERT INTO HORARIO_FUNCIONAMENTO
 (DIA_SEMANA, EM_FUNCIONAMENTO, HORA_ABERTURA, HORA_FECHAMENTO, ABERTURA_FERIADO, FECHAMENTO_FERIADO)
VALUES (5, 1, '19:00', '23:59', '19:00', '23:59');
INSERT INTO HORARIO_FUNCIONAMENTO
 (DIA_SEMANA, EM_FUNCIONAMENTO, HORA_ABERTURA, HORA_FECHAMENTO, ABERTURA_FERIADO, FECHAMENTO_FERIADO)
VALUES (6, 1, '19:00', '23:59', '19:00', '23:59');
INSERT INTO HORARIO_FUNCIONAMENTO
 (DIA_SEMANA, EM_FUNCIONAMENTO, HORA_ABERTURA, HORA_FECHAMENTO, ABERTURA_FERIADO, FECHAMENTO_FERIADO)
VALUES (7, 1, '19:00', '23:59', '19:00', '23:59');

-- Inserindo Mesas
INSERT INTO MESAS (NUMERO) VALUES (1);
INSERT INTO MESAS (NUMERO) VALUES (2);
INSERT INTO MESAS (NUMERO) VALUES (3);
INSERT INTO MESAS (NUMERO) VALUES (4);
INSERT INTO MESAS (NUMERO) VALUES (5);
INSERT INTO MESAS (NUMERO) VALUES (6);

-- Inserindo Gerentes
INSERT INTO GERENTES (CODIGO, NOME) VALUES (SEQ_GERENTES.NEXTVAL, 'Maria');
INSERT INTO GERENTES (CODIGO, NOME) VALUES (SEQ_GERENTES.NEXTVAL, 'Francisco');
INSERT INTO GERENTES (CODIGO, NOME) VALUES (SEQ_GERENTES.NEXTVAL, 'Camila');

-- Inserindo Atendentes
INSERT INTO ATENDENTES (CODIGO, NOME, COD_GERENTE) VALUES (SEQ_ATENDENTES.NEXTVAL, 'Bruna', 1);
INSERT INTO ATENDENTES (CODIGO, NOME, COD_GERENTE) VALUES (SEQ_ATENDENTES.NEXTVAL, 'Joana', 1);
INSERT INTO ATENDENTES (CODIGO, NOME, COD_GERENTE) VALUES (SEQ_ATENDENTES.NEXTVAL, 'Pedro', 2);
INSERT INTO ATENDENTES (CODIGO, NOME, COD_GERENTE) VALUES (SEQ_ATENDENTES.NEXTVAL, 'Mariana', 2);
INSERT INTO ATENDENTES (CODIGO, NOME, COD_GERENTE) VALUES (SEQ_ATENDENTES.NEXTVAL, 'Jorge', 3);

-- Inserindo Clientes
INSERT INTO CLIENTES (CODIGO, NOME, TELEFONE) VALUES (SEQ_CLIENTES.NEXTVAL, 'Jamil', '3331-0001');
INSERT INTO CLIENTES (CODIGO, NOME, TELEFONE) VALUES (SEQ_CLIENTES.NEXTVAL, 'Lineu', '3332-0002');
INSERT INTO CLIENTES (CODIGO, NOME, TELEFONE) VALUES (SEQ_CLIENTES.NEXTVAL, 'Rubens', '3333-0003');

-- Inserindo Estoque
INSERT INTO ESTOQUE (CODIGO, QUANTIDADE) VALUES (SEQ_ESTOQUE.NEXTVAL, 20);
INSERT INTO ESTOQUE (CODIGO, QUANTIDADE) VALUES (SEQ_ESTOQUE.NEXTVAL, 30);
INSERT INTO ESTOQUE (CODIGO, QUANTIDADE) VALUES (SEQ_ESTOQUE.NEXTVAL, 10);
INSERT INTO ESTOQUE (CODIGO, QUANTIDADE) VALUES (SEQ_ESTOQUE.NEXTVAL, 15);
INSERT INTO ESTOQUE (CODIGO, QUANTIDADE) VALUES (SEQ_ESTOQUE.NEXTVAL, 20);
INSERT INTO ESTOQUE (CODIGO, QUANTIDADE) VALUES (SEQ_ESTOQUE.NEXTVAL, 8);
INSERT INTO ESTOQUE (CODIGO, QUANTIDADE) VALUES (SEQ_ESTOQUE.NEXTVAL, 10);
INSERT INTO ESTOQUE (CODIGO, QUANTIDADE) VALUES (SEQ_ESTOQUE.NEXTVAL, 15);
INSERT INTO ESTOQUE (CODIGO, QUANTIDADE) VALUES (SEQ_ESTOQUE.NEXTVAL, 12);
INSERT INTO ESTOQUE (CODIGO, QUANTIDADE) VALUES (SEQ_ESTOQUE.NEXTVAL, 10);
INSERT INTO ESTOQUE (CODIGO, QUANTIDADE) VALUES (SEQ_ESTOQUE.NEXTVAL, 10);
INSERT INTO ESTOQUE (CODIGO, QUANTIDADE) VALUES (SEQ_ESTOQUE.NEXTVAL, 15);

-- Inserindo Itens
INSERT INTO ITENS (CODIGO, DESCRICAO, VALOR, COD_ESTOQUE) VALUES (SEQ_ITENS.NEXTVAL, 'Batata', 1.50, 1);
INSERT INTO ITENS (CODIGO, DESCRICAO, VALOR, COD_ESTOQUE) VALUES (SEQ_ITENS.NEXTVAL, 'Linguiça Calabresa', 2.50, 2);
INSERT INTO ITENS (CODIGO, DESCRICAO, VALOR, COD_ESTOQUE) VALUES (SEQ_ITENS.NEXTVAL, 'Cebola', 0.80, 3);
INSERT INTO ITENS (CODIGO, DESCRICAO, VALOR, COD_ESTOQUE) VALUES (SEQ_ITENS.NEXTVAL, 'Limão', 0.30, 4);
INSERT INTO ITENS (CODIGO, DESCRICAO, VALOR, COD_ESTOQUE) VALUES (SEQ_ITENS.NEXTVAL, 'Couve', 0.10, 5);
INSERT INTO ITENS (CODIGO, DESCRICAO, VALOR, COD_ESTOQUE) VALUES (SEQ_ITENS.NEXTVAL, 'Abacaxi', 1.50, 6);

-- Inserindo Opções
INSERT INTO OPCOES (CODIGO, DESCRICAO, PCT_LUCRO, TIPO) VALUES (SEQ_OPCOES.NEXTVAL, 'Porção de batatas fritas', 0.10, 'C');
INSERT INTO OPCOES (CODIGO, DESCRICAO, PCT_LUCRO, TIPO) VALUES (SEQ_OPCOES.NEXTVAL, 'Porção de calabresa acebolada', 0.20, 'C');
INSERT INTO OPCOES (CODIGO, DESCRICAO, PCT_LUCRO, TIPO) VALUES (SEQ_OPCOES.NEXTVAL, 'Suco verde', 0.00, 'B');
INSERT INTO OPCOES (CODIGO, DESCRICAO, PCT_LUCRO, TIPO) VALUES (SEQ_OPCOES.NEXTVAL, 'Vinho Malbec', 0.10, 'P');
INSERT INTO OPCOES (CODIGO, DESCRICAO, PCT_LUCRO, TIPO) VALUES (SEQ_OPCOES.NEXTVAL, 'Vinho Salton', 0.10, 'P');
INSERT INTO OPCOES (CODIGO, DESCRICAO, PCT_LUCRO, TIPO) VALUES (SEQ_OPCOES.NEXTVAL, 'Vinho Piagentini', 0.10, 'P');
INSERT INTO OPCOES (CODIGO, DESCRICAO, PCT_LUCRO, TIPO) VALUES (SEQ_OPCOES.NEXTVAL, 'Água Mineral Lindoya 500ml', 0.00, 'P');
INSERT INTO OPCOES (CODIGO, DESCRICAO, PCT_LUCRO, TIPO) VALUES (SEQ_OPCOES.NEXTVAL, 'Coca-cola Lata', 0.10, 'P');
INSERT INTO OPCOES (CODIGO, DESCRICAO, PCT_LUCRO, TIPO) VALUES (SEQ_OPCOES.NEXTVAL, 'Guarana Antarctica', 0.10, 'P');

-- Inserindo Bebidas Prontas
INSERT INTO BEBIDAS_PRONTAS (CODIGO, VALOR, COD_ESTOQUE) VALUES (4, 45.00, 7); -- 'Vinho Malbec'
INSERT INTO BEBIDAS_PRONTAS (CODIGO, VALOR, COD_ESTOQUE) VALUES (5, 23.00, 8); -- 'Vinho Salton'
INSERT INTO BEBIDAS_PRONTAS (CODIGO, VALOR, COD_ESTOQUE) VALUES (6, 30.00, 9); -- 'Vinho Piagentini'
INSERT INTO BEBIDAS_PRONTAS (CODIGO, VALOR, COD_ESTOQUE) VALUES (7, 2.50, 10); -- 'Água Mineral Lindoya 500ml'
INSERT INTO BEBIDAS_PRONTAS (CODIGO, VALOR, COD_ESTOQUE) VALUES (8, 2.80, 11); -- 'Coca-cola Lata'
INSERT INTO BEBIDAS_PRONTAS (CODIGO, VALOR, COD_ESTOQUE) VALUES (9, 2.60, 12); -- 'Guaraná Antarctica'

-- Inserindo Vinhos
INSERT INTO VINHOS (CODIGO, SAFRA, TIPO_UVA) VALUES (4, 1960, 'Tannat');
INSERT INTO VINHOS (CODIGO, SAFRA, TIPO_UVA) VALUES (5, 2000, 'Prosecco');
INSERT INTO VINHOS (CODIGO, SAFRA, TIPO_UVA) VALUES (6, 1990, 'Merlot');

-- Inserindo Comidas
INSERT INTO COMIDAS (CODIGO) VALUES (1);
INSERT INTO COMIDAS (CODIGO) VALUES (2);

-- Inserindo Bebidas
INSERT INTO BEBIDAS (CODIGO) VALUES (3);

-- Inserindo Itens de Comida
INSERT INTO COMIDA_ITENS (COD_COMIDA, COD_ITEM, QUANTIDADE) VALUES (1, 1, 2);
INSERT INTO COMIDA_ITENS (COD_COMIDA, COD_ITEM, QUANTIDADE) VALUES (2, 2, 2);
INSERT INTO COMIDA_ITENS (COD_COMIDA, COD_ITEM, QUANTIDADE) VALUES (2, 3, 1);

-- Inserindo Itens de Bebida
INSERT INTO BEBIDA_ITENS (COD_BEBIDA, COD_ITEM, QUANTIDADE) VALUES (3, 4, 1);
INSERT INTO BEBIDA_ITENS (COD_BEBIDA, COD_ITEM, QUANTIDADE) VALUES (3, 5, 1);
INSERT INTO BEBIDA_ITENS (COD_BEBIDA, COD_ITEM, QUANTIDADE) VALUES (3, 6, 1);

COMMIT;
