-- Inserindo Horário de Funcionamento
INSERT INTO HORARIO_FUNCIONAMENTO (DIA_SEMANA, EM_FUNCIONAMENTO, HORA_ABERTURA, HORA_FECHAMENTO, ABERTURA_FERIADO, FECHAMENTO_FERIADO)
VALUES (1, 1, '19:00', '23:59', '19:00', '23:59');
INSERT INTO HORARIO_FUNCIONAMENTO (DIA_SEMANA, EM_FUNCIONAMENTO, HORA_ABERTURA, HORA_FECHAMENTO, ABERTURA_FERIADO, FECHAMENTO_FERIADO)
VALUES (2, 0, NULL, NULL, NULL, NULL);
INSERT INTO HORARIO_FUNCIONAMENTO (DIA_SEMANA, EM_FUNCIONAMENTO, HORA_ABERTURA, HORA_FECHAMENTO, ABERTURA_FERIADO, FECHAMENTO_FERIADO)
VALUES (3, 1, '19:00', '23:59', '19:00', '23:59');
INSERT INTO HORARIO_FUNCIONAMENTO (DIA_SEMANA, EM_FUNCIONAMENTO, HORA_ABERTURA, HORA_FECHAMENTO, ABERTURA_FERIADO, FECHAMENTO_FERIADO)
VALUES (4, 1, '19:00', '23:59', '19:00', '23:59');
INSERT INTO HORARIO_FUNCIONAMENTO (DIA_SEMANA, EM_FUNCIONAMENTO, HORA_ABERTURA, HORA_FECHAMENTO, ABERTURA_FERIADO, FECHAMENTO_FERIADO)
VALUES (5, 1, '19:00', '23:59', '19:00', '23:59');
INSERT INTO HORARIO_FUNCIONAMENTO (DIA_SEMANA, EM_FUNCIONAMENTO, HORA_ABERTURA, HORA_FECHAMENTO, ABERTURA_FERIADO, FECHAMENTO_FERIADO)
VALUES (6, 1, '19:00', '23:59', '19:00', '23:59');
INSERT INTO HORARIO_FUNCIONAMENTO (DIA_SEMANA, EM_FUNCIONAMENTO, HORA_ABERTURA, HORA_FECHAMENTO, ABERTURA_FERIADO, FECHAMENTO_FERIADO)
VALUES (7, 1, '19:00', '23:59', '19:00', '23:59');
