CREATE OR REPLACE PACKAGE BODY FUNCIONAMENTO_RESTAURANTE AS
  FUNCTION SEMANA_NUMERO(
      DIA_ATUAL DATE)
  RETURN NUMBER IS
  BEGIN
      RETURN TO_CHAR(DIA_ATUAL, 'D');
  END;
  
  FUNCTION RESTAURANTE_ABERTO(
    HORA_CONSULTA DATE)
  RETURN NUMBER IS
    V_DIA_ABERTO NUMBER(1);
    V_HORA_ABERTURA VARCHAR2(5);
    V_HORA_FECHAMENTO VARCHAR2(5);
    V_ABERTO NUMBER(1) := 0;
  BEGIN
    SELECT EM_FUNCIONAMENTO, HORA_ABERTURA, HORA_FECHAMENTO
    INTO V_DIA_ABERTO, V_HORA_ABERTURA, V_HORA_FECHAMENTO
    FROM HORARIO_FUNCIONAMENTO
    WHERE DIA_SEMANA = SEMANA_NUMERO(HORA_CONSULTA);
  
    IF(V_DIA_ABERTO = '1') THEN
      IF(TO_CHAR(HORA_CONSULTA, 'HH24:MI') BETWEEN V_HORA_ABERTURA AND V_HORA_FECHAMENTO)  THEN
        V_ABERTO := 1;
      END IF;
    END IF;
    RETURN V_ABERTO;
  END;
  
  FUNCTION RESTAURANTE_ABERTO_FERIADO(
    HORA_CONSULTA DATE)
  RETURN NUMBER IS
    V_DIA_ABERTO NUMBER(1);
    V_HORA_ABERTURA VARCHAR2(5);
    V_HORA_FECHAMENTO VARCHAR2(5);
    V_ABERTO NUMBER(1) := 0;
  BEGIN
    SELECT EM_FUNCIONAMENTO, ABERTURA_FERIADO, FECHAMENTO_FERIADO
    INTO V_DIA_ABERTO, V_HORA_ABERTURA, V_HORA_FECHAMENTO
    FROM HORARIO_FUNCIONAMENTO
    WHERE DIA_SEMANA = SEMANA_NUMERO(HORA_CONSULTA);
  
    IF(V_DIA_ABERTO = '1') THEN
      IF(TO_CHAR(HORA_CONSULTA, 'HH24:MI') BETWEEN V_HORA_ABERTURA AND V_HORA_FECHAMENTO)  THEN
        V_ABERTO := 1;
      END IF;
    END IF;
    RETURN V_ABERTO;
  END;
  
  PROCEDURE ADICIONAR_RESERVA(
    COD_CLIENTE CLIENTES.CODIGO%TYPE,
    NRO_MESA NUMBER,
    HORARIO_RESERVA DATE)
  IS
    RESTAURANTE_ABERTO NUMBER(1) := RESTAURANTE_ABERTO(HORARIO_RESERVA);
    RESTAURANTE_ABERTO_FERIADO NUMBER(1) := RESTAURANTE_ABERTO_FERIADO(HORARIO_RESERVA);
    
    COUNT_RESERVA NUMBER;
    COUNT_MESA NUMBER;
    
    INSERT_LISTA_ESPERA EXCEPTION;
    RESTAURANTE_FECHADO EXCEPTION;
    MESA_OCUPADA EXCEPTION;
    
  BEGIN
    IF(RESTAURANTE_ABERTO = 1) THEN
      IF(RESTAURANTE_ABERTO_FERIADO = 1) THEN 
        SELECT COUNT(*) INTO COUNT_RESERVA
        FROM RESERVAS;
          IF(COUNT_RESERVA < 6) THEN
            SELECT COUNT(NUM_MESA) INTO COUNT_MESA
            FROM RESERVAS
            WHERE NUM_MESA = NRO_MESA;
            
            IF(COUNT_MESA = 0) THEN
              INSERT INTO RESERVA
              VALUES(COD_CLIENTE, NRO_MESA, HORARIO_RESERVA);
            ELSE
              RAISE MESA_OCUPADA;
            END IF;
          ELSE
            RAISE INSERT_LISTA_ESPERA;
            
            INSERT INTO LISTA_ESPERA
            VALUES(SYSDATE, COD_CLIENTE, HORARIO_RESERVA);
          END IF;
        END IF;
    ELSE
      RAISE RESTAURANTE_FECHADO;
    END IF;
    
  EXCEPTION
    WHEN INSERT_LISTA_ESPERA THEN
      DBMS_OUTPUT.PUT_LINE('Não há mesas disponíveis. Cliente inserido na lista de espera.');
      
    WHEN RESTAURANTE_FECHADO THEN
      DBMS_OUTPUT.PUT_LINE('O restaurante não abre na data passada.');
      
    WHEN MESA_OCUPADA THEN
      DBMS_OUTPUT.PUT_LINE('A mesa desejada já está ocupada');
  END;

END FUNCIONAMENTO_RESTAURANTE;